# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

from fastapi import FastAPI
from fastramqpi.events import GraphQLEvents
from fastramqpi.main import FastRAMQPI

from os2mo_nexus import depends
from os2mo_nexus.autogenerated_graphql_client import GraphQLClient
from os2mo_nexus.config import Settings


def create_app() -> FastAPI:
    settings = Settings()

    fastramqpi = FastRAMQPI(
        application_name="nexus",
        settings=settings.fastramqpi,
        graphql_version=30,
        graphql_client_cls=GraphQLClient,
        graphql_events=GraphQLEvents(
            declare_namespaces=[],
            declare_listeners=[],
        ),
    )
    fastramqpi.add_context(settings=settings)

    # FastAPI router
    app = fastramqpi.get_app()

    @app.get("/test")
    async def test(graphql_client: depends.GraphQLClient) -> str:
        root = await graphql_client.get_root()
        return root.user_key

    return app
