# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from typing import Annotated

from fastapi import Depends
from fastramqpi.depends import from_user_context
from fastramqpi.ramqp.depends import from_context

from os2mo_nexus.autogenerated_graphql_client import GraphQLClient as _GraphQLClient
from os2mo_nexus.nexus.api import NexusAPI as _NexusAPI

GraphQLClient = Annotated[_GraphQLClient, Depends(from_context("graphql_client"))]
NexusAPI = Annotated[_NexusAPI, Depends(from_user_context("nexus_api"))]
