# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from collections.abc import AsyncIterator

import pytest
from fastapi import FastAPI
from httpx import AsyncClient
from respx import MockRouter

from os2mo_nexus.app import create_app
from os2mo_nexus.autogenerated_graphql_client import GraphQLClient


@pytest.fixture(
    params=[
        pytest.param(
            None,
            marks=pytest.mark.envvar(
                {
                    # NEXUS__OIDC__CLIENT_SECRET is provided either by
                    # nexus.env or GitLab CI.
                    "NEXUS__URL": "https://unity.nexus-test.kmd.dk",
                    "NEXUS__OIDC__CLIENT_ID": "third-party-client",
                    "NEXUS__OIDC__TOKEN_ENDPOINT": "https://iam.nexus-test.kmd.dk/authx/realms/unity/protocol/openid-connect/token",
                }
            ),
        )
    ]
)
async def app() -> FastAPI:
    """Override the FastRAMQPI `app` fixture.

    The FastRAMQPI `test_client`/`server` fixtures run this app under a real
    uvicorn server on 127.0.0.1:8000, so the GraphQL event system delivers MO
    events to it and the integration reacts to them automatically.
    """
    return create_app()


@pytest.fixture
async def graphql_client(mo_client: AsyncClient) -> AsyncIterator[GraphQLClient]:
    """Authenticated GraphQL codegen client for OS2mo test setup and assertions."""
    async with GraphQLClient(
        url=f"{mo_client.base_url}/graphql/v30", http_client=mo_client
    ) as client:
        yield client


@pytest.fixture(autouse=True)
def passthrough_nexus(respx_mock: MockRouter) -> None:
    """Allow calls to KMD Nexus."""
    respx_mock.route(host="iam.nexus-test.kmd.dk").pass_through()
    respx_mock.route(host="unity.nexus-test.kmd.dk").pass_through()
