# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import pytest
from httpx import AsyncClient

from os2mo_nexus.autogenerated_graphql_client import GraphQLClient


@pytest.mark.integration_test
async def test_nothing_1() -> None:
    assert True


@pytest.mark.integration_test
async def test_nothing_2() -> None:
    assert True


@pytest.mark.integration_test
async def test_test(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
) -> None:
    r = await test_client.get("/test")
    assert r.json() == "root"
