# Generated by ariadne-codegen on 2026-09-30 16:41
# Source: queries.graphql

from .base_model import BaseModel


class GetRoot(BaseModel):
    org: "GetRootOrg"


class GetRootOrg(BaseModel):
    user_key: str


GetRoot.update_forward_refs()
GetRootOrg.update_forward_refs()
